<script setup>
	const props = defineProps(['params'])
</script>

<template>	
	<div class="flex items-center -space-x-4 hover:space-x-1">
		<button v-if="params.data.jobStatus == 'accepted'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-blue-600 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">accepted</button>
    <button v-else-if="params.data.jobStatus == 'quoted'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-purple-600 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out">quoted</button>
    <button v-else-if="params.data.jobStatus == 'done'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-green-500 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out">done</button>
    <button v-else-if="params.data.jobStatus == 'cancelled'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-red-600 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out">cancelled</button>
    <button v-else-if="params.data.jobStatus == 'no parts'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-yellow-500 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-yellow-600 hover:shadow-lg focus:bg-yellow-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-yellow-700 active:shadow-lg transition duration-150 ease-in-out">no parts</button>
    <button v-else-if="params.data.jobStatus == 'quoting'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-blue-400 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-blue-500 hover:shadow-lg focus:bg-blue-500 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-600 active:shadow-lg transition duration-150 ease-in-out">quoting</button>
    <button v-else-if="params.data.jobStatus == 'scheduled'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-emerald-200 text-black font-thin text-sm leading-tight rounded-full shadow-md hover:bg-emerald-300 hover:shadow-lg focus:bg-gray-300 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-emerald-400 active:shadow-lg transition duration-150 ease-in-out">scheduled</button>
    <button v-else-if="params.data.jobStatus == 'pending'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-gray-800 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-gray-900 hover:shadow-lg focus:bg-gray-900 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-gray-900 active:shadow-lg transition duration-150 ease-in-out">pending</button>
    <button v-else-if="params.data.jobStatus == 'invoiced'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-green-800 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-green-900 hover:shadow-lg focus:bg-green-900 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-900 active:shadow-lg transition duration-150 ease-in-out">invoiced</button>
    <button v-else-if="params.data.jobStatus == 'follow-up'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-yellow-800 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-yellow-900 hover:shadow-lg focus:bg-yellow-900 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-yellow-900 active:shadow-lg transition duration-150 ease-in-out">follow-up</button>
    <button v-else-if="params.data.jobStatus == 'paid'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-green-500 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-green-600 hover:shadow-lg focus:bg-green-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-700 active:shadow-lg transition duration-150 ease-in-out">paid</button>
    <button v-else-if="params.data.jobStatus == 'to order parts'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-yellow-500 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-yellow-600 hover:shadow-lg focus:bg-yellow-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-yellow-700 active:shadow-lg transition duration-150 ease-in-out">to order parts</button>
    <button v-else-if="params.data.jobStatus == 'parts ordered'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-yellow-400 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-yellow-500 hover:shadow-lg focus:bg-yellow-500 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-yellow-600 active:shadow-lg transition duration-150 ease-in-out">parts ordered</button>
    <button v-else-if="params.data.jobStatus == 'parts arrived'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-yellow-300 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-yellow-400 hover:shadow-lg focus:bg-yellow-400 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-yellow-500 active:shadow-lg transition duration-150 ease-in-out">parts arrived</button>
    <button v-else-if="params.data.jobStatus == 'parts installed'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-yellow-200 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-yellow-300 hover:shadow-lg focus:bg-yellow-300 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-yellow-400 active:shadow-lg transition duration-150 ease-in-out">parts installed</button>
    <button v-else-if="params.data.jobStatus == 'parts paid'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-yellow-100 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-yellow-200 hover:shadow-lg focus:bg-yellow-200 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-yellow-300 active:shadow-lg transition duration-150 ease-in-out">parts paid</button>
    <button v-else-if="params.data.jobStatus == 'parts not paid'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-red-100 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-red-200 hover:shadow-lg focus:bg-red-200 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-300 active:shadow-lg transition duration-150 ease-in-out">parts not paid</button>
    <button v-else-if="params.data.jobStatus == 'parts not installed'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-red-200 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-red-300 hover:shadow-lg focus:bg-red-300 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-400 active:shadow-lg transition duration-150 ease-in-out">parts not installed</button>
    <button v-else-if="params.data.jobStatus == 'parts not ordered'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-red-300 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-red-400 hover:shadow-lg focus:bg-red-400 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-500 active:shadow-lg transition duration-150 ease-in-out">parts not ordered</button>
    <button v-else-if="params.data.jobStatus == 'parts not available'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-red-400 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-red-500 hover:shadow-lg focus:bg-red-500 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-600 active:shadow-lg transition duration-150 ease-in-out">parts not available</button>
    <button v-else-if="params.data.jobStatus == 'parts not needed'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-red-500 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-red-600 hover:shadow-lg focus:bg-red-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-700 active:shadow-lg transition duration-150 ease-in-out">parts not needed</button>
    <button v-else-if="params.data.jobStatus == 'parts not found'" type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 bg-red-600 text-white font-thin text-sm leading-tight rounded-full shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out">parts not found</button>
    <button v-else type="button" class="mt-1 inline-block px-3 w-[135px] py-1.5 border-2 border-gray-800 text-gray-800 font-thin text-sm leading-tight rounded-full hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out">{{params.data.jobStatus || ' - '}}</button>
	</div>	
</template>